version: "3.7"

services:
  react-test-app:
    build:
      context: "./"
      args:
        - NODE_ENV=production
        - PORT=80
      target: prod
    image: "kgrondin01/react-test-app"
    working_dir: /code
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
